image: kondayutarou/lecture-list:latest

services:
  - docker:dind

stages:
  - build

variables:
  LANGUAGE: "en_GB:en_US:ja_JA"
  LC_ALL: "en_GB.UTF-8"
  LANG: "en_GB.UTF-8"
  GOOGLE_DRIVE_KEY: $google_drive_key

build:
  stage: build
  before_script:
    - touch google_drive_key.json
    - echo "$GOOGLE_DRIVE_KEY" | xxd -r -p - > google_drive_key.json
  script:
    - ls
    - bundle install
    - bundle exec fastlane build_and_upload_apk
