# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a Debug Build"
  lane :build do
    gradle(task: "assemble", build_type: "Debug")
    original_output_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    updated_output_path = "~/Desktop/Debug-#{get_current_date}.apk"

    sh("mv #{original_output_path} #{updated_output_path}")
    puts("Apk location: #{updated_output_path}")
  end

  def get_current_date
    Date.today
  end
end
