# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build and Upload a Debug Build"
  lane :build_and_upload_apk do
    gradle(task: "assemble", build_type: "Debug")
    original_output_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

    new_path = rename(original_output_path)
    sh("mv #{original_output_path} #{new_path}")
    puts("Apk location: #{new_path}")
    upload(file_name: new_path)
  end

  private_lane :upload do |options|
    upload_to_google_drive(
      drive_keyfile: 'google_drive_key.json',
      service_account: true,
      folder_id: '1DbZ9ARq856nGB4S48ZdAJdjVhzB711bP',
      upload_files: [options[:file_name]]
    )
    puts("#{lane_context[SharedValues::GDRIVE_UPLOADED_FILE_NAMES]} uploaded to #{lane_context[SharedValues::GDRIVE_UPLOADED_FILE_URLS]}")
  end

  def rename (original_path)
    pattern = /^(.*\/)(.*.apk)$/
    match = pattern.match(original_path)
    apk_folder_path = match[1]
    apk_name = match[2]
    new_apk_name = "#{lane_context[SharedValues::GRADLE_BUILD_TYPE]}-#{android_get_version_name}[#{android_get_version_code}]-#{Date.today.strftime("%Y%m%d")}.apk"
    return apk_folder_path + new_apk_name
  end
end
